queensfordcollege/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('timetable.urls') ),
    path('admin/', admin.site.urls),
]

timetable/urls.py
from django.urls import path
from . import views


app_name="timetable"
urlpatterns = [
    path('',views.index, name='index'),
    path('qualification',views.list_qualification, name='qualification'),
    path('timetable/<str:national_code>',views.timetable, name='timetable'),

]

timetable/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.



class state(models.Model):
    state_name=models.CharField(max_length=60)

    def __str__(self):
        return self.state_name

class campus(models.Model):
    state=models.ForeignKey(state, on_delete=models.CASCADE)
    campus_name=models.CharField(max_length=60)
    campus_email=models.EmailField(max_length=30)
    campus_phone=models.CharField(max_length=60)
    campus_address=models.CharField(max_length=100)
    campus_manager=models.CharField(max_length=60)


    def __str__(self):
        return self.campus_name

USAGE_RECOMMENDATION = {
        ("CURRENT", "CURRENT"),
        ("SUPERSESEDED", "SUPERSESEDED"),
       }

TERM = {
        ("Semester 1 Term 1", "Semester 1 Term 1"),
        ("Semester 1 Term 2", "Semester 1 Term 2"),
        ("Semester 2 Term 1", "Semester 2 Term 1"),
        ("Semester 2 Term 2", "Semester 2 Term 2"),
        ("Semester 3 Term 1", "Semester 3 Term 1"),
        ("Semester 3 Term 2", "Semester 3 Term 2"),
        ("Semester 4 Term 1", "Semester 4 Term 1"),
        ("Semester 4 Term 2", "Semester 4 Term 2"),

       }

class Qualification(models.Model):
    national_code = models.CharField(max_length=10)
    qualification_name = models.CharField(max_length=60)
    usage_recommendation = models.CharField(max_length=50, choices=USAGE_RECOMMENDATION)
    total_duration = models.IntegerField()
    total_core_units = models.IntegerField()
    total_elective_units = models.IntegerField()
    total_units = models.IntegerField()
    term = models.CharField(max_length=100, choices=TERM)
    start_date=models.DateField()
    proposed=models.DateField()
    intake_date=models.DateField()





    def __str__(self):

        return self.national_code
        return self.qualification_name




STATUS = {
        ("CORE", "CORE"),
        ("ELECTIVE", "ELECTIVE"),
       }







class Units(models.Model):
    qualification = models.ForeignKey(Qualification, on_delete=models.CASCADE, null=True,  related_name='Qualification.national_code +' )
    unit_code = models.CharField(max_length=15)
    unit_name = models.CharField(max_length=100)
    status = models.CharField(max_length=50, choices=STATUS)
    duration = models.IntegerField()



    def __str__(self):
        return self.unit_name





class Break(models.Model):
    weeks = models.IntegerField()
    title = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField()
    def __str__(self):
         return self.title

timetable/views.py
import datetime

from django.shortcuts import render
from bs4 import BeautifulSoup
import requests
from . models import *
from datetime import datetime
from datetime import timedelta
import datetime
from django.http import HttpResponse


# Create your views here.

def index(request):
    return render(request, 'Index.html')


def list_qualification(request):
    qualifications = Qualification.objects.all()
    context={
        'qualifications': qualifications
    }


    return render(request, 'qualification.html',context)

def qualification(request):
    if request.method =="GET" :
        qualification=request.GET.get('qualification')
        html_test= requests.get(f'https://training.gov.au/Training/Details/{qualification}').text
        soup=BeautifulSoup(html_test, 'lxml')
        Usage_recommendation=soup.find('div', class_='display-field')
        #mapping=soup.find('div', class_='display-field-info')

        #print(Usage_recommendation)
    return render(request, 'quali.html')



def timetable(request,national_code):

    dates = Units.objects.filter(qualification__national_code = national_code)
    count = Units.objects.filter(qualification__national_code = national_code).count()
    qualif=Qualification.objects.all(national_code =  national_code)
    for qualify in qualif:
        unit_start=qualify.start_date


    startdate=[]
    enddate = []
    assignmentdate = []
    classhour=[]



    for date in dates:

        start_date =unit_start
        end_date = unit_start + timedelta(weeks=date.duration) - timedelta(days=1)
        assignment_date =unit_start + timedelta(weeks=date.duration) - timedelta(days=1) +  timedelta(days=14)
        assignment = assignment_date.strftime("%d-%b-%Y")
        end = end_date.strftime("%d-%b-%Y")
        enddate.append(end)
        assignmentdate.append(assignment)
        class_hour = date.duration * 20
        classhour.append(class_hour)
















    context={
        'dates': dates,
        'end': enddate,
        'assignmentdate' : assignmentdate,
        'classhour': classhour





    }
    return render(request, 'timetable.html',context)

templates/Index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>




</head>
<body>

<h1>Welcome to queensford College Students</h1>


<a href="qualification" >Let go to search Qualifications </a>

</body>
</html>

templates/qualification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of qualifications</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</head>
<body>
<center> <h2> List of Qualifications  </h2> </center>
<table class="table table-info table-striped-columns">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">National_code</th>
      <th scope="col">Qualification_Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  {% for qualification in  qualifications %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{qualification.national_code}}</td>
      <td>{{qualification.qualification_name}}</td>

      <td><a href="{% url 'timetable:timetable' qualification.national_code %} " class=" btn btn-primary">View Timetable</a></td>
    </tr>


  {% endfor %}
  </tbody>


</table>

</body>
</html>

templates/qualifications.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</head>
<body>
<center> <h1> Welcome students  </h1></center>

<center> <h2> Search qualifications   </h2></center>


<form method="GET">
    {% csrf_token %}
  <div class="mb-4">
    <label for="exampleInputEmail1" class="form-label">Search  Qualifications</label>
    <input type="test" class="form-control" id="exampleInputEmail1"  name="qualification" aria-describedby="emailHelp" placeholder="Enter National Code of Qualification ">
  </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>



</body>
</html>

templates/timetable.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</head>
<body>



<table  class="table table-success table-striped-columns">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Week</th>
      <th scope="col">Unit Code</th>
      <th scope="col">Unit of Competetency</th>
      <th scope="col">Core/Elective</th>
      <th scope="col">Duration</th>
      <th scope="col">Class Hour</th>
      <th scope="col">Unit Start</th>
      <th scope="col">Unit End Date</th>
      <th scope="col">Assignment Deu Date</th>
    </tr>
  </thead>
  <tbody>
  {% for date in dates  %}


    <tr>

      <th scope="row">{{forloop.counter}}</th>
      <td>{{date.qualification}}</td>
      <td>{{date.unit_code}}</td>
      <td>{{date.unit_name}}</td>
      <td>{{date.status}}</td>
      <td>{{date.duration}}</td>


       {% for enn in classhour  %}
        {% if forloop.counter == forloop.parentloop.counter %}
      <td>{{ enn }}</td>
      {% endif %}
      {% endfor %}


      <td>{{date.unit_start_date}}</td>
      {% for enn in end  %}
        {% if forloop.counter == forloop.parentloop.counter %}
      <td>{{ enn }}</td>
      {% endif %}
      {% endfor %}


      {% for assignmen in assignmentdate %}
       {% if forloop.counter == forloop.parentloop.counter %}
      <td>{{assignmen}}</td>
       {% endif %}
       {% endfor %}




    </tr>

  {% endfor %}



  </tbody>



</body>
</html>